version: '3.3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
  postgres:
    image: bitnami/postgresql:12.5.0
    environment:
      POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE
      POSTGRESQL_USERNAME: $POSTGRESQL_USERNAME
      POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
    ports:
      - "15432:5432"
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      REACT_APP_OKTA_HOST_NAME: $OKTA_HOST_NAME
      REACT_APP_OKTA_FRONTEND_CLIENT_ID: $OKTA_FRONTEND_CLIENT_ID
    ports:
      - 3000:3000
    
  backend:
    build: ./backend-api
    volumes:
      - ./backend-api/target/asterisk-backend-api-0.0.1-SNAPSHOT.jar:/app/asterisk-backend-api.jar
    environment:
      OKTA_HOST_NAME: $OKTA_HOST_NAME
      OKTA_BACKEND_CLIENT_ID: $OKTA_BACKEND_CLIENT_ID
      OKTA_BACKEND_CLIENT_SECRET: $OKTA_BACKEND_CLIENT_SECRET
      POSTGRES_HOST: $POSTGRESQL_HOST 
      POSTGRES_PORT: $POSTGRESQL_PORT 
      POSTGRES_DATABASE: $POSTGRESQL_DATABASE
      POSTGRES_USERNAME: $POSTGRESQL_USERNAME
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      LOCAL_DEV_PORT: 8080
    ports:
      - 8080:8080

  asterisk:
    build: .
    ports:
      - 5060:5060
      - 6000-7000:6000-7000
    volumes:
      - ./configs:/etc/asterisk
    environment:
      HOST_IP: $HOST_IP
      POSTGRESQL_HOST: $POSTGRESQL_HOST 
      POSTGRESQL_PORT: $POSTGRESQL_PORT 
      POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE
      POSTGRESQL_USERNAME: $POSTGRESQL_USERNAME
      POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
    depends_on:
      - postgres