version: '3.3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  postgres:
    image: bitnami/postgresql:12.5.0
    environment:
      POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE
      POSTGRESQL_USERNAME: $POSTGRESQL_USERNAME
      POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
    ports:
      - "15432:5432"
    restart: unless-stopped
  asterisk:
    build: .
    ports:
      - 5060:5060
      - 6000-7000:6000-7000
    volumes:
      - ./configs:/etc/asterisk
    environment:
      HOST_IP: $HOST_IP
      POSTGRESQL_HOST: $POSTGRESQL_HOST 
      POSTGRESQL_PORT: $POSTGRESQL_PORT 
      POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE
      POSTGRESQL_USERNAME: $POSTGRESQL_USERNAME
      POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD
    depends_on:
      - postgres