spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:15432}/${POSTGRES_DATABASE:asterisk}
    username: ${POSTGRES_USER:asterisk}
    password: ${POSTGRES_PASSWORD:asterisk}
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
    hikari:
      schema: ${POSTGRES_SCHEMA:public}
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        types:
          print:
            banner: false
server:
  max-http-header-size: 256KB
  port: ${LOCAL_DEV_PORT:8080}
  servlet:
    context-path: /api/v1/
okta:
  oauth2:
    issuer: https://${OKTA_HOST_NAME:dev-96574323}.okta.com/oauth2/default
    client-id: ${OKTA_BACKEND_CLIENT_ID:0oa547oumsDb0W8Xa5d7}
    client-secret: ${OKTA_BACKEND_CLIENT_SECRET:WrArMLNagAog2H07tbFVYaWYdToPo8ci61yvl4A9}
    scopes: openid
    roles-claim: groups